[package]
name = "steam-vent"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[dependencies]
steam-vent-proto = { version = "0.1", path = "./protobuf" }
steam-vent-crypto = { version = "0.1", path = "./crypto" }
tokio = { version = "1.0", features = ["net", "io-util"] }
tokio-stream = "0.1"
binread = "1.4"
binwrite = "0.2"
thiserror = "1.0"
bytes = "1.0"
protobuf = "=2.18.1"
bytemuck = "1.4"
crc = "1.8"
byteorder = "1.3"
flate2 = "1.0"

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt", "rt-multi-thread"] }

[workspace]