[package]
name = "steam-vent-crypto"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"
license = "MIT"

[dependencies]
rand = "0.7"
rsa = "0.3"
once_cell = "1.5"
aes = "0.6"
thiserror = "1.0"
block-modes = "0.7"
sha-1 = "0.9"
hmac = "0.10"
base64 = "0.13"

[dev-dependencies]
steam-vent = { version = "0.1", path = ".." }